import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

from sqlalchemy import create_engine, inspect
from sqlmodel import Session


sys.path.insert(0, str(Path(__file__).resolve().parent))

from app.migrations import adapt_statement_for_dialect, run_migrations  # noqa: E402
from app.models import AttendanceRecord, TaskLog, TeamWorkLog, User, WorkFormSubmission  # noqa: E402
from app.use_cases.record_trash import purge_expired_deleted_records  # noqa: E402


EXPECTED_TABLES = {
    "department",
    "registrationverification",
    "user",
    "site",
    "attendancerecord",
    "tasklog",
    "tasktemplate",
    "workform",
    "workformsubmission",
    "teamworklog",
    "teamworklogentry",
    "auditevent",
    "schema_migrations",
}


def make_engine(db_path: Path):
    return create_engine(
        f"sqlite:///{db_path.as_posix()}",
        connect_args={"check_same_thread": False},
    )


def columns(engine, table_name: str):
    return {
        column["name"]
        for column in inspect(engine).get_columns(table_name)
    }


def column_details(engine, table_name: str):
    return {
        column["name"]: column
        for column in inspect(engine).get_columns(table_name)
    }


def assert_contains(label: str, actual, expected):
    missing = set(expected) - set(actual)

    if missing:
        raise AssertionError(f"{label}: missing {sorted(missing)}")


def assert_migration_recorded(engine):
    with engine.begin() as connection:
        rows = connection.exec_driver_sql(
            "SELECT version FROM schema_migrations ORDER BY version"
        ).all()

    expected_versions = [
        "0001_initial_schema",
        "0002_work_form_photo_metadata",
        "0003_departments",
        "0004_registration_verification",
        "0005_dashboard_department_preference",
        "0006_manual_attendance_entries",
        "0007_record_rubbish_bin",
        "0008_manual_task_logs",
        "0009_worker_classes_and_team_logs",
        "0010_pdf_daywork_form_template",
        "0011_multi_team_daywork_form",
        "0012_form_and_team_log_rubbish_bin",
        "0013_daywork_team_break_options",
    ]
    if [row[0] for row in rows] != expected_versions:
        raise AssertionError(f"schema_migrations: expected {expected_versions}")


def test_postgres_statement_adaptation():
    statement = """
    CREATE TABLE IF NOT EXISTS tasklog (
        id INTEGER PRIMARY KEY,
        created_at DATETIME NOT NULL
    )
    """

    adapted = adapt_statement_for_dialect(statement, "postgresql")

    if "GENERATED BY DEFAULT AS IDENTITY" not in adapted:
        raise AssertionError("postgres statement adaptation: expected identity primary key")
    if "TIMESTAMP WITH TIME ZONE" not in adapted:
        raise AssertionError("postgres statement adaptation: expected timezone timestamp")
    if adapt_statement_for_dialect(statement, "sqlite") != statement:
        raise AssertionError("postgres statement adaptation: sqlite statements should be unchanged")

    print("ok - postgres statement adaptation")


def test_fresh_database():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as directory:
        engine = make_engine(Path(directory) / "fresh.db")

        applied = run_migrations(engine)
        expected_versions = [
            "0001_initial_schema",
            "0002_work_form_photo_metadata",
            "0003_departments",
            "0004_registration_verification",
            "0005_dashboard_department_preference",
            "0006_manual_attendance_entries",
            "0007_record_rubbish_bin",
            "0008_manual_task_logs",
            "0009_worker_classes_and_team_logs",
            "0010_pdf_daywork_form_template",
            "0011_multi_team_daywork_form",
            "0012_form_and_team_log_rubbish_bin",
            "0013_daywork_team_break_options",
        ]
        if applied != expected_versions:
            raise AssertionError(f"fresh migration: expected {expected_versions}, got {applied}")

        if run_migrations(engine) != []:
            raise AssertionError("fresh migration: second run should be a no-op")

        assert_contains("fresh tables", inspect(engine).get_table_names(), EXPECTED_TABLES)
        assert_contains(
            "fresh tasklog columns",
            columns(engine, "tasklog"),
            {
                "department_id",
                "work_date",
                "hours_worked",
                "safety_notes",
                "photo_urls",
                "status",
                "client_submission_id",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
                "entry_source",
                "created_by_supervisor_id",
            },
        )
        assert_contains(
            "fresh attendance columns",
            columns(engine, "attendancerecord"),
            {
                "department_id",
                "distance_from_site_m",
                "within_site_radius",
                "client_submission_id",
                "entry_source",
                "created_by_supervisor_id",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
            },
        )
        attendance_columns = column_details(engine, "attendancerecord")
        if not attendance_columns["latitude"]["nullable"] or not attendance_columns["longitude"]["nullable"]:
            raise AssertionError("fresh attendance columns: manual entries require nullable coordinates")
        assert_contains(
            "fresh form submission columns",
            columns(engine, "workformsubmission"),
            {
                "department_id",
                "photo_metadata",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
            },
        )
        assert_contains(
            "fresh user columns",
            columns(engine, "user"),
            {"department_id", "dashboard_department_id", "is_global_admin"},
        )
        assert_contains(
            "fresh user worker class",
            columns(engine, "user"),
            {"worker_class"},
        )
        assert_contains(
            "fresh team work log columns",
            columns(engine, "teamworklog"),
            {
                "department_id",
                "leader_id",
                "week_start",
                "notes",
                "client_submission_id",
                "status",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
                "created_at",
            },
        )
        assert_contains(
            "fresh team work log entry columns",
            columns(engine, "teamworklogentry"),
            {"team_work_log_id", "worker_id", "site_id", "work_date", "start_time", "end_time", "break_minutes", "hours_worked", "work_description"},
        )
        assert_contains(
            "fresh registration verification columns",
            columns(engine, "registrationverification"),
            {"email", "name", "code_hash", "token_hash", "attempts", "expires_at", "verified_at", "consumed_at"},
        )
        assert_contains("fresh site columns", columns(engine, "site"), {"department_id"})
        assert_contains("fresh workform columns", columns(engine, "workform"), {"department_id"})
        assert_migration_recorded(engine)
        engine.dispose()

    print("ok - fresh database migration")


def test_legacy_database():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as directory:
        engine = make_engine(Path(directory) / "legacy.db")

        with engine.begin() as connection:
            connection.exec_driver_sql(
                """
                CREATE TABLE "user" (
                    id INTEGER PRIMARY KEY,
                    email VARCHAR NOT NULL,
                    name VARCHAR NOT NULL,
                    password_hash VARCHAR NOT NULL,
                    role VARCHAR NOT NULL
                )
                """
            )
            connection.exec_driver_sql(
                """
                CREATE TABLE tasklog (
                    id INTEGER PRIMARY KEY,
                    worker_id INTEGER NOT NULL,
                    site_id INTEGER,
                    description VARCHAR NOT NULL,
                    photo_url VARCHAR,
                    created_at DATETIME NOT NULL
                )
                """
            )
            connection.exec_driver_sql(
                """
                CREATE TABLE attendancerecord (
                    id INTEGER PRIMARY KEY,
                    worker_id INTEGER NOT NULL,
                    site_id INTEGER,
                    record_type VARCHAR NOT NULL,
                    latitude FLOAT NOT NULL,
                    longitude FLOAT NOT NULL,
                    accuracy FLOAT,
                    note VARCHAR,
                    photo_url VARCHAR,
                    status VARCHAR NOT NULL,
                    created_at DATETIME NOT NULL
                )
                """
            )
            connection.exec_driver_sql(
                """
                CREATE TABLE workformsubmission (
                    id INTEGER PRIMARY KEY,
                    form_id INTEGER NOT NULL,
                    worker_id INTEGER NOT NULL,
                    site_id INTEGER,
                    work_date VARCHAR,
                    answers_json VARCHAR NOT NULL,
                    photo_urls VARCHAR,
                    created_at DATETIME NOT NULL
                )
                """
            )

        applied = run_migrations(engine)
        expected_versions = [
            "0001_initial_schema",
            "0002_work_form_photo_metadata",
            "0003_departments",
            "0004_registration_verification",
            "0005_dashboard_department_preference",
            "0006_manual_attendance_entries",
            "0007_record_rubbish_bin",
            "0008_manual_task_logs",
            "0009_worker_classes_and_team_logs",
            "0010_pdf_daywork_form_template",
            "0011_multi_team_daywork_form",
            "0012_form_and_team_log_rubbish_bin",
            "0013_daywork_team_break_options",
        ]
        if applied != expected_versions:
            raise AssertionError(f"legacy migration: expected {expected_versions}, got {applied}")

        assert_contains("legacy tables", inspect(engine).get_table_names(), EXPECTED_TABLES)
        assert_contains(
            "legacy user columns",
            columns(engine, "user"),
            {"status", "department_id", "dashboard_department_id", "is_global_admin", "worker_class"},
        )
        assert_contains(
            "legacy registration verification columns",
            columns(engine, "registrationverification"),
            {"email", "name", "code_hash", "token_hash", "attempts", "expires_at", "verified_at", "consumed_at"},
        )
        assert_contains(
            "legacy tasklog columns",
            columns(engine, "tasklog"),
            {
                "department_id",
                "work_date",
                "hours_worked",
                "safety_notes",
                "photo_urls",
                "status",
                "client_submission_id",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
                "entry_source",
                "created_by_supervisor_id",
            },
        )
        assert_contains(
            "legacy attendance columns",
            columns(engine, "attendancerecord"),
            {
                "department_id",
                "distance_from_site_m",
                "within_site_radius",
                "client_submission_id",
                "entry_source",
                "created_by_supervisor_id",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
            },
        )
        attendance_columns = column_details(engine, "attendancerecord")
        if not attendance_columns["latitude"]["nullable"] or not attendance_columns["longitude"]["nullable"]:
            raise AssertionError("legacy attendance columns: manual entries require nullable coordinates")
        assert_contains(
            "legacy form submission columns",
            columns(engine, "workformsubmission"),
            {
                "department_id",
                "status",
                "client_submission_id",
                "photo_metadata",
                "deleted_at",
                "deleted_by_supervisor_id",
                "deletion_reason",
            },
        )
        assert_contains(
            "legacy team work log columns",
            columns(engine, "teamworklog"),
            {"deleted_at", "deleted_by_supervisor_id", "deletion_reason"},
        )
        assert_migration_recorded(engine)
        engine.dispose()

    print("ok - legacy database migration")


def test_rubbish_bin_purge():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as directory:
        engine = make_engine(Path(directory) / "trash.db")
        run_migrations(engine)
        now = datetime.now(timezone.utc)

        with Session(engine) as session:
            supervisor = User(
                department_id=1,
                email="trash-supervisor@example.com",
                name="Trash Supervisor",
                password_hash="test",
                role="supervisor",
            )
            session.add(supervisor)
            session.flush()
            expired_attendance = AttendanceRecord(
                department_id=1,
                worker_id=999,
                record_type="check_in",
                latitude=-36.8,
                longitude=174.7,
                status="approved",
                deleted_at=now - timedelta(days=31),
                deleted_by_supervisor_id=supervisor.id,
                deletion_reason="Expired duplicate",
            )
            retained_task = TaskLog(
                department_id=1,
                worker_id=999,
                description="Retained deleted task",
                status="approved",
                deleted_at=now - timedelta(days=29),
                deleted_by_supervisor_id=supervisor.id,
                deletion_reason="Recent duplicate",
            )
            expired_form_submission = WorkFormSubmission(
                department_id=1,
                form_id=1,
                worker_id=999,
                answers_json="{}",
                status="approved",
                deleted_at=now - timedelta(days=31),
                deleted_by_supervisor_id=supervisor.id,
                deletion_reason="Expired duplicate",
            )
            retained_team_log = TeamWorkLog(
                department_id=1,
                leader_id=999,
                week_start="2026-06-29",
                status="approved",
                deleted_at=now - timedelta(days=29),
                deleted_by_supervisor_id=supervisor.id,
                deletion_reason="Recent duplicate",
            )
            session.add(expired_attendance)
            session.add(retained_task)
            session.add(expired_form_submission)
            session.add(retained_team_log)
            session.commit()
            expired_id = expired_attendance.id
            retained_id = retained_task.id
            expired_form_id = expired_form_submission.id
            retained_team_log_id = retained_team_log.id

            counts = purge_expired_deleted_records(session, now)
            if (
                counts["attendance"] != 1
                or counts["task"] != 0
                or counts["form"] != 1
                or counts["team_log"] != 0
            ):
                raise AssertionError(f"rubbish bin purge: unexpected counts {counts}")
            if session.get(AttendanceRecord, expired_id) is not None:
                raise AssertionError("rubbish bin purge: expired attendance should be permanently deleted")
            if session.get(TaskLog, retained_id) is None:
                raise AssertionError("rubbish bin purge: records under 30 days must be retained")
            if session.get(WorkFormSubmission, expired_form_id) is not None:
                raise AssertionError("rubbish bin purge: expired form submission should be permanently deleted")
            if session.get(TeamWorkLog, retained_team_log_id) is None:
                raise AssertionError("rubbish bin purge: recent team logs must be retained")

        engine.dispose()

    print("ok - rubbish bin 30-day purge")


def main():
    test_postgres_statement_adaptation()
    test_fresh_database()
    test_legacy_database()
    test_rubbish_bin_purge()
    print("migration test passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
