import sys
import tempfile
from pathlib import Path

from sqlalchemy import create_engine, inspect


sys.path.insert(0, str(Path(__file__).resolve().parent))

from app.migrations import adapt_statement_for_dialect, run_migrations  # noqa: E402


EXPECTED_TABLES = {
    "department",
    "registrationverification",
    "user",
    "site",
    "attendancerecord",
    "tasklog",
    "tasktemplate",
    "workform",
    "workformsubmission",
    "auditevent",
    "schema_migrations",
}


def make_engine(db_path: Path):
    return create_engine(
        f"sqlite:///{db_path.as_posix()}",
        connect_args={"check_same_thread": False},
    )


def columns(engine, table_name: str):
    return {
        column["name"]
        for column in inspect(engine).get_columns(table_name)
    }


def assert_contains(label: str, actual, expected):
    missing = set(expected) - set(actual)

    if missing:
        raise AssertionError(f"{label}: missing {sorted(missing)}")


def assert_migration_recorded(engine):
    with engine.begin() as connection:
        rows = connection.exec_driver_sql(
            "SELECT version FROM schema_migrations ORDER BY version"
        ).all()

    expected_versions = [
        "0001_initial_schema",
        "0002_work_form_photo_metadata",
        "0003_departments",
        "0004_registration_verification",
    ]
    if [row[0] for row in rows] != expected_versions:
        raise AssertionError(f"schema_migrations: expected {expected_versions}")


def test_postgres_statement_adaptation():
    statement = """
    CREATE TABLE IF NOT EXISTS tasklog (
        id INTEGER PRIMARY KEY,
        created_at DATETIME NOT NULL
    )
    """

    adapted = adapt_statement_for_dialect(statement, "postgresql")

    if "GENERATED BY DEFAULT AS IDENTITY" not in adapted:
        raise AssertionError("postgres statement adaptation: expected identity primary key")
    if "TIMESTAMP WITH TIME ZONE" not in adapted:
        raise AssertionError("postgres statement adaptation: expected timezone timestamp")
    if adapt_statement_for_dialect(statement, "sqlite") != statement:
        raise AssertionError("postgres statement adaptation: sqlite statements should be unchanged")

    print("ok - postgres statement adaptation")


def test_fresh_database():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as directory:
        engine = make_engine(Path(directory) / "fresh.db")

        applied = run_migrations(engine)
        expected_versions = [
            "0001_initial_schema",
            "0002_work_form_photo_metadata",
            "0003_departments",
            "0004_registration_verification",
        ]
        if applied != expected_versions:
            raise AssertionError(f"fresh migration: expected {expected_versions}, got {applied}")

        if run_migrations(engine) != []:
            raise AssertionError("fresh migration: second run should be a no-op")

        assert_contains("fresh tables", inspect(engine).get_table_names(), EXPECTED_TABLES)
        assert_contains(
            "fresh tasklog columns",
            columns(engine, "tasklog"),
            {"department_id", "work_date", "hours_worked", "safety_notes", "photo_urls", "status", "client_submission_id"},
        )
        assert_contains(
            "fresh attendance columns",
            columns(engine, "attendancerecord"),
            {"department_id", "distance_from_site_m", "within_site_radius", "client_submission_id"},
        )
        assert_contains(
            "fresh form submission columns",
            columns(engine, "workformsubmission"),
            {"department_id", "photo_metadata"},
        )
        assert_contains("fresh user columns", columns(engine, "user"), {"department_id", "is_global_admin"})
        assert_contains(
            "fresh registration verification columns",
            columns(engine, "registrationverification"),
            {"email", "name", "code_hash", "token_hash", "attempts", "expires_at", "verified_at", "consumed_at"},
        )
        assert_contains("fresh site columns", columns(engine, "site"), {"department_id"})
        assert_contains("fresh workform columns", columns(engine, "workform"), {"department_id"})
        assert_migration_recorded(engine)
        engine.dispose()

    print("ok - fresh database migration")


def test_legacy_database():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as directory:
        engine = make_engine(Path(directory) / "legacy.db")

        with engine.begin() as connection:
            connection.exec_driver_sql(
                """
                CREATE TABLE "user" (
                    id INTEGER PRIMARY KEY,
                    email VARCHAR NOT NULL,
                    name VARCHAR NOT NULL,
                    password_hash VARCHAR NOT NULL,
                    role VARCHAR NOT NULL
                )
                """
            )
            connection.exec_driver_sql(
                """
                CREATE TABLE tasklog (
                    id INTEGER PRIMARY KEY,
                    worker_id INTEGER NOT NULL,
                    site_id INTEGER,
                    description VARCHAR NOT NULL,
                    photo_url VARCHAR,
                    created_at DATETIME NOT NULL
                )
                """
            )
            connection.exec_driver_sql(
                """
                CREATE TABLE attendancerecord (
                    id INTEGER PRIMARY KEY,
                    worker_id INTEGER NOT NULL,
                    site_id INTEGER,
                    record_type VARCHAR NOT NULL,
                    latitude FLOAT NOT NULL,
                    longitude FLOAT NOT NULL,
                    accuracy FLOAT,
                    note VARCHAR,
                    photo_url VARCHAR,
                    status VARCHAR NOT NULL,
                    created_at DATETIME NOT NULL
                )
                """
            )
            connection.exec_driver_sql(
                """
                CREATE TABLE workformsubmission (
                    id INTEGER PRIMARY KEY,
                    form_id INTEGER NOT NULL,
                    worker_id INTEGER NOT NULL,
                    site_id INTEGER,
                    work_date VARCHAR,
                    answers_json VARCHAR NOT NULL,
                    photo_urls VARCHAR,
                    created_at DATETIME NOT NULL
                )
                """
            )

        applied = run_migrations(engine)
        expected_versions = [
            "0001_initial_schema",
            "0002_work_form_photo_metadata",
            "0003_departments",
            "0004_registration_verification",
        ]
        if applied != expected_versions:
            raise AssertionError(f"legacy migration: expected {expected_versions}, got {applied}")

        assert_contains("legacy tables", inspect(engine).get_table_names(), EXPECTED_TABLES)
        assert_contains("legacy user columns", columns(engine, "user"), {"status", "department_id", "is_global_admin"})
        assert_contains(
            "legacy registration verification columns",
            columns(engine, "registrationverification"),
            {"email", "name", "code_hash", "token_hash", "attempts", "expires_at", "verified_at", "consumed_at"},
        )
        assert_contains(
            "legacy tasklog columns",
            columns(engine, "tasklog"),
            {"department_id", "work_date", "hours_worked", "safety_notes", "photo_urls", "status", "client_submission_id"},
        )
        assert_contains(
            "legacy attendance columns",
            columns(engine, "attendancerecord"),
            {"department_id", "distance_from_site_m", "within_site_radius", "client_submission_id"},
        )
        assert_contains(
            "legacy form submission columns",
            columns(engine, "workformsubmission"),
            {"department_id", "status", "client_submission_id", "photo_metadata"},
        )
        assert_migration_recorded(engine)
        engine.dispose()

    print("ok - legacy database migration")


def main():
    test_postgres_statement_adaptation()
    test_fresh_database()
    test_legacy_database()
    print("migration test passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
