from __future__ import annotations

import argparse
import hashlib
import importlib.util
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from types import ModuleType

from sqlalchemy import inspect, text
from sqlalchemy.engine import Connection, Engine

from app.config import BACKEND_DIR


MIGRATIONS_DIR = BACKEND_DIR / "migrations" / "versions"


class MigrationError(RuntimeError):
    pass


@dataclass(frozen=True)
class Migration:
    version: str
    name: str
    checksum: str
    module: ModuleType


class MigrationContext:
    def __init__(self, connection: Connection):
        self.connection = connection

    def execute(self, statement: str):
        self.connection.exec_driver_sql(
            adapt_statement_for_dialect(statement, self.connection.dialect.name)
        )

    def table_exists(self, table_name: str) -> bool:
        return table_name in inspect(self.connection).get_table_names()

    def column_exists(self, table_name: str, column_name: str) -> bool:
        if not self.table_exists(table_name):
            return False

        return any(
            column["name"] == column_name
            for column in inspect(self.connection).get_columns(table_name)
        )

    def add_column_if_missing(self, table_name: str, column_name: str, definition: str):
        if self.column_exists(table_name, column_name):
            return

        table = self._quote_identifier(table_name)
        column = self._quote_identifier(column_name)
        self.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")

    def _quote_identifier(self, identifier: str) -> str:
        return self.connection.dialect.identifier_preparer.quote(identifier)


def adapt_statement_for_dialect(statement: str, dialect_name: str) -> str:
    if dialect_name != "postgresql":
        return statement

    return (
        statement
        .replace("id INTEGER PRIMARY KEY", "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        .replace("created_at DATETIME NOT NULL", "created_at TIMESTAMP WITH TIME ZONE NOT NULL")
        .replace("DATETIME", "TIMESTAMP WITH TIME ZONE")
    )


def _validate_migration_history(migrations: list[Migration], applied: dict[str, str], *, require_current: bool):
    expected = {migration.version: migration.checksum for migration in migrations}
    unknown = set(applied) - set(expected)
    if unknown:
        raise MigrationError(
            "Database has migrations not included in this release: "
            + ", ".join(sorted(unknown))
            + ". Use a compatible backend image; do not rewrite migration history."
        )
    for version, checksum in applied.items():
        if checksum != expected[version]:
            raise MigrationError(f"Migration {version} has changed since it was applied")
    missing = [migration.version for migration in migrations if migration.version not in applied]
    if require_current and missing:
        raise MigrationError(
            "Database migrations are pending: "
            + ", ".join(missing)
            + ". Run python -m app.migrations as a separate release step before starting the backend."
        )


def verify_migrations(connection: Connection, migrations_dir: Path = MIGRATIONS_DIR) -> None:
    """Check this image's exact migration history without creating or changing data."""
    migrations = _load_migrations(migrations_dir)
    if "schema_migrations" not in inspect(connection).get_table_names():
        raise MigrationError(
            "Database migration history is missing. Run python -m app.migrations "
            "as a separate release step before starting the backend."
        )
    _validate_migration_history(migrations, _get_applied_migrations(connection), require_current=True)


def run_migrations(engine: Engine, migrations_dir: Path = MIGRATIONS_DIR) -> list[str]:
    migrations = _load_migrations(migrations_dir)
    applied_now: list[str] = []

    with engine.begin() as connection:
        _ensure_migration_table(connection)
        applied = _get_applied_migrations(connection)
        # Check all recorded history before running any pending upgrade.
        _validate_migration_history(migrations, applied, require_current=False)

        for migration in migrations:
            if migration.version in applied:
                continue

            upgrade = getattr(migration.module, "upgrade", None)

            if not callable(upgrade):
                raise MigrationError(f"Migration {migration.name} has no upgrade(context) function")

            upgrade(MigrationContext(connection))
            connection.execute(
                text(
                    """
                INSERT INTO schema_migrations (version, name, checksum, applied_at)
                VALUES (:version, :name, :checksum, :applied_at)
                """
                ),
                {
                    "version": migration.version,
                    "name": migration.name,
                    "checksum": migration.checksum,
                    "applied_at": datetime.now(timezone.utc).isoformat(),
                },
            )
            applied_now.append(migration.version)

    return applied_now


def _ensure_migration_table(connection: Connection):
    connection.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version VARCHAR PRIMARY KEY,
            name VARCHAR NOT NULL,
            checksum VARCHAR NOT NULL,
            applied_at VARCHAR NOT NULL
        )
        """
    )


def _get_applied_migrations(connection: Connection) -> dict[str, str]:
    rows = connection.exec_driver_sql(
        "SELECT version, checksum FROM schema_migrations"
    ).all()
    return {row[0]: row[1] for row in rows}


def _load_migrations(migrations_dir: Path) -> list[Migration]:
    if not migrations_dir.exists():
        raise MigrationError("Bundled migration files are missing; deploy a complete backend image")

    migrations = [
        _load_migration(path)
        for path in sorted(migrations_dir.glob("*.py"))
        if path.name != "__init__.py"
    ]
    versions = [migration.version for migration in migrations]

    if not migrations:
        raise MigrationError("Bundled migration files are empty; deploy a complete backend image")
    if len(versions) != len(set(versions)):
        raise MigrationError("Duplicate migration versions found")

    return migrations


def _load_migration(path: Path) -> Migration:
    module_name = f"app_migration_{path.stem}"
    spec = importlib.util.spec_from_file_location(module_name, path)

    if not spec or not spec.loader:
        raise MigrationError(f"Could not load migration {path.name}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    version = getattr(module, "revision", path.stem)

    return Migration(
        version=version,
        name=path.name,
        checksum=hashlib.sha256(path.read_bytes()).hexdigest(),
        module=module,
    )


def main() -> int:
    from app.database import engine

    parser = argparse.ArgumentParser(description="Apply or verify backend database migrations.")
    parser.add_argument("--check", action="store_true", help="Verify exact migration history without applying migrations.")
    args = parser.parse_args()
    if args.check:
        with engine.connect() as connection:
            verify_migrations(connection)
        print("Database migrations match this backend release")
        return 0

    applied = run_migrations(engine)

    if applied:
        print(f"Applied migrations: {', '.join(applied)}")
    else:
        print("No pending migrations")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
